version: '3'

services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/home/node
      - ~/.ssh:/.ssh-localhost:ro
    working_dir: /home/node
